name: wavelet_tf_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aiohttp=3.9.3=py38h2bbff1b_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - astroid=2.14.2=py38haa95532_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - blinker=1.7.0=pyhd8ed1ab_0
  - brotli=1.0.9=ha925a31_2
  - brotli-python=1.0.9=py38h885f38d_7
  - ca-certificates=2023.12.12=haa95532_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.2=pyhd8ed1ab_0
  - certifi=2024.2.2=py38haa95532_0
  - cffi=1.16.0=py38h2bbff1b_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=win_pyh7428d3b_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=41.0.3=py38h3438e0d_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dill=0.3.7=py38haa95532_0
  - flatbuffers=2.0.0=h6c2663c_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h546665d_1
  - frozenlist=1.4.0=py38h2bbff1b_0
  - gast=0.4.0=pyh9f0ad1d_0
  - giflib=5.2.1=h8d14728_2
  - glib=2.69.1=h5dc1a3c_2
  - google-auth=2.28.0=pyhca7485f_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpcio=1.42.0=py38hc60d5dd_0
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - h5py=3.7.0=nompi_py38hc790250_100
  - hdf5=1.12.1=nompi_h2a0e4a3_100
  - icu=58.2=ha925a31_3
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - intel-openmp=2024.0.0=h57928b3_49841
  - isort=5.9.3=pyhd3eb1b0_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h8ffe710_2
  - keras=2.10.0=py38haa95532_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py38hd77b12b_0
  - lazy-object-proxy=1.6.0=py38h2bbff1b_0
  - lerc=3.0=hd77b12b_0
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libclang=12.0.0=default_h627e005_2
  - libcurl=8.5.0=h86230a5_0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_0
  - libiconv=1.17=h8ffe710_0
  - liblapack=3.9.0=8_mkl
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libssh2=1.10.0=hcd4344a_2
  - libtiff=4.5.1=hd77b12b_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.5.2=pyhd8ed1ab_0
  - matplotlib=3.5.3=py38haa244fe_2
  - matplotlib-base=3.5.3=py38he529843_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mkl=2020.4=hb70f87d_311
  - msys2-conda-epoch=20160418=1
  - multidict=6.0.4=py38h2bbff1b_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - numpy=1.22.4=py38h1d2777f_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=1.1.1w=h2bbff1b_0
  - opt_einsum=3.3.0=pyhc1e730c_2
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=1.2.3=py38h4c96930_0
  - pcre=8.45=h0e60522_0
  - pillow=10.2.0=py38h2bbff1b_0
  - platformdirs=3.10.0=py38haa95532_0
  - ply=3.11=py_1
  - protobuf=3.20.3=py38haa244fe_1
  - pyasn1=0.5.1=pyhd8ed1ab_0
  - pyasn1-modules=0.3.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pylint=2.16.2=py38haa95532_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyqt=5.15.10=py38hd77b12b_0
  - pyqt5-sip=12.13.0=py38h2bbff1b_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.8.18=h6244533_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-flatbuffers=23.5.26=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2024.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywavelets=1.4.1=py38h2bbff1b_0
  - qt-main=5.15.2=he8e5bd7_7
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scikit-learn=0.22.1=py38h7208079_1
  - scipy=1.7.3=py38ha1292f7_0
  - seaborn=0.12.2=py38haa95532_0
  - setuptools=59.8.0=py38haa244fe_1
  - sip=6.7.12=py38hd77b12b_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h6c2663c_1
  - sqlite=3.41.2=h2bbff1b_0
  - tensorboard=2.10.0=py38haa95532_0
  - tensorboard-data-server=0.6.1=py38haa95532_0
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.10.0=mkl_py38ha5c4042_0
  - tensorflow-base=2.10.0=mkl_py38h6a7f48e_0
  - tensorflow-estimator=2.10.0=py38haa95532_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.1=py38haa95532_0
  - tornado=6.2=py38h294d835_0
  - typing-extensions=4.9.0=hd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - werkzeug=2.1.2=pyhd8ed1ab_1
  - wheel=0.41.2=py38haa95532_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - wrapt=1.14.1=py38h2bbff1b_0
  - xz=5.4.5=h8cc25b3_0
  - yapf=0.40.2=py38haa95532_0
  - yarl=1.7.2=py38h294d835_2
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - filelock==3.13.1
      - fsspec==2024.2.0
      - huggingface-hub==0.20.3
      - pip==24.0
      - pyyaml==6.0.1
      - tqdm==4.66.2
prefix: ...